export const names = [
  "Sonic Sanctuary",
  "The Beat Box",
  "Melody Machine",
  "Rhythm Reactor",
  "Sound Sphere",
  "The Music Vault",
  "Harmony Hub",
  "Tune Tornado",
  "Bass Station",
  "The Groove Box",
  "Echo Chamber",
  "Sonic Boom",
  "The Mix Master",
  "Frequency Fighter",
  "Sound Wave",
  "The Beat Factory",
  "Rhythm Rocket",
  "Melody Mixer",
  "The Audio Arcade",
  "Sound Storm",
  "The Tune Tank",
  "Beat Blaster",
  "Sonic Spinner",
  "The Music Matrix",
  "Harmony Haven",
  "Rhythm Revolution",
  "The Sound Sanctuary",
  "Melody Madness",
  "Beat Bazaar",
  "The Sonic Sphere",
  "Audio Adventure",
  "The Rhythm Realm",
  "Sound Spectrum",
  "The Beat Brigade",
  "Melody Manor",
  "Sonic Symphony",
  "The Groove Galaxy",
  "Rhythm Rocket Ship",
  "Sound Safari",
  "The Beat Bunker",
  "Melody Mountain",
  "Sonic Stadium",
  "The Audio Arena",
  "Rhythm Ranch",
  "Sound Station",
  "The Beat Boulevard",
  "Melody Metropolis",
  "Sonic Skyscraper",
  "The Groove Garden",
  "Rhythm Rapids",
  "Sound Saloon",
  "The Beat Barn",
  "Melody Mill",
  "Sonic Submarine",
  "The Audio Attic",
  "Rhythm Retreat",
  "Sound Shack",
  "The Beat Bistro",
  "Melody Mansion",
  "Sonic Space Station",
  "The Groove Garage",
  "Rhythm Resort",
  "Sound Studio",
  "The Beat Bakery",
  "Melody Museum",
  "Sonic Subway",
  "The Audio Academy",
  "Rhythm Restaurant",
  "Sound Showroom",
  "The Beat Boutique",
  "Melody Market",
  "Sonic Sidewalk",
  "The Groove Gallery",
  "Rhythm Railroad",
  "Sound Superstore",
  "The Beat Bank",
  "Melody Mall",
  "Sonic Speedway",
  "The Audio Airport",
  "Rhythm Raceway",
  "Sound Stadium",
  "The Beat Beach",
  "Melody Marina",
  "Sonic Starship",
  "The Groove Greenhouse",
  "Rhythm River",
  "Sound Seaport",
  "The Beat Boardwalk",
  "Melody Mine",
  "Sonic Satellite",
  "The Audio Amphitheater",
  "Rhythm Refinery",
  "Sound Skyline",
  "The Beat Bridge",
  "Melody Meadow",
  "Sonic Spaceship",
  "The Groove Grotto",
  "Rhythm Ridge",
  "Sound Summit",
  "The Beat Basement",
  "Melody Maze",
  "Sonic Street",
  "The Audio Alley",
];

export const usernames = [
  "CaptainQuirk",
  "TheJellyfish",
  "CosmicCucumber",
  "SirReginald",
  "DoctorDapper",
  "TheFunkyMonk",
  "ProfessorPixel",
  "MadamMystic",
  "AgentArgon",
  "BaronVonBubbles",
  "CountCatnip",
  "DukeOfDoodles",
  "EmperorEmu",
  "LordLlama",
  "KingKoala",
  "QueenQuokka",
  "PrincePenguin",
  "PrincessPanda",
  "DuchessDuck",
  "GeneralGiraffe",
  "MajorMeerkat",
  "SergeantSloth",
  "CorporalCorgi",
  "PrivatePlatypus",
  "AdmiralAlpaca",
  "CadetCapybara",
  "CaptainChameleon",
  "CommanderCobra",
  "LieutenantLemur",
  "EnsignEchidna",
  "OfficerOcelot",
  "WardenWombat",
  "RangerRaccoon",
  "ScoutSquirrel",
  "TrackerTarsier",
  "ExplorerErmine",
  "VoyagerVulture",
  "PioneerPangolin",
  "TrailblazerTapir",
  "PathfinderPorcupine",
  "TheWhimsicalWalrus",
  "TheMysticalMeerkat",
  "TheSillySalamander",
  "TheJollyJellyfish",
  "TheDapperDolphin",
  "TheQuirkyQuail",
  "TheZanyZebra",
  "TheWackyWombat",
  "TheGoofyGorilla",
  "TheHappyHippo",
  "TheLaughingLlama",
  "TheDancingDingo",
  "TheSingingSloth",
  "ThePrancingPony",
  "TheGallopingGazelle",
  "TheSoaringSeagull",
  "TheFloatingFlamingo",
  "TheBouncingBunny",
  "TheHoppingHedgehog",
  "TheWaddlingWombat",
  "TheProwlingPanther",
  "TheStalkingStork",
  "TheFlyingFox",
  "TheGlidingGecko",
  "TheLeapingLemur",
  "TheSwingingSpider",
  "TheCrawlingCrab",
  "TheCreepingCaterpillar",
  "TheFlutteringButterfly",
  "TheBuzzingBee",
  "TheChirpingCricket",
  "TheCroakingFrog",
  "TheHootingOwl",
  "TheHowlingWolf",
  "TheRoaringLion",
  "TheGrowlingBear",
  "TheSnortingBoar",
  "TheSqueakingMouse",
  "TheChatteringChipmunk",
  "TheGibberingGibbon",
  "TheBabblingBaboon",
  "TheMumblingManatee",
  "TheWhisperingWalrus",
  "TheGrumblingGrizzly",
  "TheRumblingRhino",
  "TheBellowingBison",
  "TheTrumpetingElephant",
];
